### ISSUE TITLE
Fjerne punktum fra filnavn

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/basisprofiler-r4#75]
StructureDefinition/no-basis-relatedperson-person-reference.StructureDefinition-extension..xml <- dobbelprikk

**Comment by thomiz** [comment]
Hm, har ikke tenkt å gjøre noe med dette.
Det er i henholdt til best practice https://simplifier.net/guide/profilingacademy/Best-practices

_When saving a profile, extend the filename with the resource type, for example: myPatient.structuredefinition-profile.xml or workedOnMonday.structuredefinition-extension.xml.

This'll help you tell the StructureDefinition files apart, which are otherwise all just the same StructureDefinition FHIR resource._

**Comment by rockphotog** [comment]
Tenkte helt på slutten: extension..xml

**Comment by thomiz** [comment]
Ah, ser det nå. Skal fikse :-)

**Comment by thomiz** [comment]
Done
https://github.com/HL7Norway/basisprofiler-r4/commit/356db855a40159d8e3230a73753814260c5b3122
